// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// analysisSnapshotsDao is the data access object for the table analysis_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type analysisSnapshotsDao struct {
	*internal.AnalysisSnapshotsDao
}

var (
	// AnalysisSnapshots is a globally accessible object for table analysis_snapshots operations.
	AnalysisSnapshots = analysisSnapshotsDao{internal.NewAnalysisSnapshotsDao()}
)

// Add your custom methods and functionality below.
