// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// analyzeJobsDao is the data access object for the table analyze_jobs.
// You can define custom methods on it to extend its functionality as needed.
type analyzeJobsDao struct {
	*internal.AnalyzeJobsDao
}

var (
	// AnalyzeJobs is a globally accessible object for table analyze_jobs operations.
	AnalyzeJobs = analyzeJobsDao{internal.NewAnalyzeJobsDao()}
)

// Add your custom methods and functionality below.
