// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// apiKeyTenantGrantsDao is the data access object for the table api_key_tenant_grants.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyTenantGrantsDao struct {
	*internal.ApiKeyTenantGrantsDao
}

var (
	// ApiKeyTenantGrants is a globally accessible object for table api_key_tenant_grants operations.
	ApiKeyTenantGrants = apiKeyTenantGrantsDao{internal.NewApiKeyTenantGrantsDao()}
)

// Add your custom methods and functionality below.
