// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// authSessionsDao is the data access object for the table auth_sessions.
// You can define custom methods on it to extend its functionality as needed.
type authSessionsDao struct {
	*internal.AuthSessionsDao
}

var (
	// AuthSessions is a globally accessible object for table auth_sessions operations.
	AuthSessions = authSessionsDao{internal.NewAuthSessionsDao()}
)

// Add your custom methods and functionality below.
