// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// communitiesDao is the data access object for the table communities.
// You can define custom methods on it to extend its functionality as needed.
type communitiesDao struct {
	*internal.CommunitiesDao
}

var (
	// Communities is a globally accessible object for table communities operations.
	Communities = communitiesDao{internal.NewCommunitiesDao()}
)

// Add your custom methods and functionality below.
