// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// emailVerificationTokensDao is the data access object for the table email_verification_tokens.
// You can define custom methods on it to extend its functionality as needed.
type emailVerificationTokensDao struct {
	*internal.EmailVerificationTokensDao
}

var (
	// EmailVerificationTokens is a globally accessible object for table email_verification_tokens operations.
	EmailVerificationTokens = emailVerificationTokensDao{internal.NewEmailVerificationTokensDao()}
)
