// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// gitCredentialsDao is the data access object for the table git_credentials.
// You can define custom methods on it to extend its functionality as needed.
type gitCredentialsDao struct {
	*internal.GitCredentialsDao
}

var (
	// GitCredentials is a globally accessible object for table git_credentials operations.
	GitCredentials = gitCredentialsDao{internal.NewGitCredentialsDao()}
)

// Add your custom methods and functionality below.
