// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// passwordResetTokensDao is the data access object for the table password_reset_tokens.
// You can define custom methods on it to extend its functionality as needed.
type passwordResetTokensDao struct {
	*internal.PasswordResetTokensDao
}

var (
	// PasswordResetTokens is a globally accessible object for table password_reset_tokens operations.
	PasswordResetTokens = passwordResetTokensDao{internal.NewPasswordResetTokensDao()}
)
