// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// planEntitlementsDao is the data access object for the table plan_entitlements.
// You can define custom methods on it to extend its functionality as needed.
type planEntitlementsDao struct {
	*internal.PlanEntitlementsDao
}

var (
	// PlanEntitlements is a globally accessible object for table plan_entitlements operations.
	PlanEntitlements = planEntitlementsDao{internal.NewPlanEntitlementsDao()}
)

// Add your custom methods and functionality below.
