// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// platformAdminsDao is the data access object for the table platform_admins.
// You can define custom methods on it to extend its functionality as needed.
type platformAdminsDao struct {
	*internal.PlatformAdminsDao
}

var (
	// PlatformAdmins is a globally accessible object for table platform_admins operations.
	PlatformAdmins = platformAdminsDao{internal.NewPlatformAdminsDao()}
)

// Add your custom methods and functionality below.
