// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// processesDao is the data access object for the table processes.
// You can define custom methods on it to extend its functionality as needed.
type processesDao struct {
	*internal.ProcessesDao
}

var (
	// Processes is a globally accessible object for table processes operations.
	Processes = processesDao{internal.NewProcessesDao()}
)

// Add your custom methods and functionality below.
