// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// processStepsDao is the data access object for the table process_steps.
// You can define custom methods on it to extend its functionality as needed.
type processStepsDao struct {
	*internal.ProcessStepsDao
}

var (
	// ProcessSteps is a globally accessible object for table process_steps operations.
	ProcessSteps = processStepsDao{internal.NewProcessStepsDao()}
)

// Add your custom methods and functionality below.
