// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// relationsDao is the data access object for the table relations.
// You can define custom methods on it to extend its functionality as needed.
type relationsDao struct {
	*internal.RelationsDao
}

var (
	// Relations is a globally accessible object for table relations operations.
	Relations = relationsDao{internal.NewRelationsDao()}
)

// Add your custom methods and functionality below.
