// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// repoBranchesDao is the data access object for the table repo_branches.
// You can define custom methods on it to extend its functionality as needed.
type repoBranchesDao struct {
	*internal.RepoBranchesDao
}

var (
	// RepoBranches is a globally accessible object for table repo_branches operations.
	RepoBranches = repoBranchesDao{internal.NewRepoBranchesDao()}
)

// Add your custom methods and functionality below.
