// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// repoAccessGrantsDao is the data access object for the table repo_access_grants.
// You can define custom methods on it to extend its functionality as needed.
type repoAccessGrantsDao struct {
	*internal.RepoAccessGrantsDao
}

var (
	// RepoAccessGrants is a globally accessible object for table repo_access_grants operations.
	RepoAccessGrants = repoAccessGrantsDao{internal.NewRepoAccessGrantsDao()}
)

// Add your custom methods and functionality below.
