// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// reposDao is the data access object for the table repos.
// You can define custom methods on it to extend its functionality as needed.
type reposDao struct {
	*internal.ReposDao
}

var (
	// Repos is a globally accessible object for table repos operations.
	Repos = reposDao{internal.NewReposDao()}
)

// Add your custom methods and functionality below.
