// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// subscriptionsDao is the data access object for the table subscriptions.
// You can define custom methods on it to extend its functionality as needed.
type subscriptionsDao struct {
	*internal.SubscriptionsDao
}

var (
	// Subscriptions is a globally accessible object for table subscriptions operations.
	Subscriptions = subscriptionsDao{internal.NewSubscriptionsDao()}
)

// Add your custom methods and functionality below.
