// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// symbolSearchDao is the data access object for the table symbol_search.
// You can define custom methods on it to extend its functionality as needed.
type symbolSearchDao struct {
	*internal.SymbolSearchDao
}

var (
	// SymbolSearch is a globally accessible object for table symbol_search operations.
	SymbolSearch = symbolSearchDao{internal.NewSymbolSearchDao()}
)

// Add your custom methods and functionality below.
