// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// symbolCommunitiesDao is the data access object for the table symbol_communities.
// You can define custom methods on it to extend its functionality as needed.
type symbolCommunitiesDao struct {
	*internal.SymbolCommunitiesDao
}

var (
	// SymbolCommunities is a globally accessible object for table symbol_communities operations.
	SymbolCommunities = symbolCommunitiesDao{internal.NewSymbolCommunitiesDao()}
)

// Add your custom methods and functionality below.
