// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// systemConfigDao is the data access object for the table system_config.
// You can define custom methods on it to extend its functionality as you wish.
type systemConfigDao struct {
	*internal.SystemConfigDao
}

var (
	// SystemConfig is globally public accessible object for table system_config operations.
	SystemConfig = systemConfigDao{
		internal.NewSystemConfigDao(),
	}
)
