// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// tenantsDao is the data access object for the table tenants.
// You can define custom methods on it to extend its functionality as needed.
type tenantsDao struct {
	*internal.TenantsDao
}

var (
	// Tenants is a globally accessible object for table tenants operations.
	Tenants = tenantsDao{internal.NewTenantsDao()}
)

// Add your custom methods and functionality below.
