// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantInvitationsDao is the data access object for the table tenant_invitations.
// You can define custom methods on it to extend its functionality as needed.
type tenantInvitationsDao struct {
	*internal.TenantInvitationsDao
}

var (
	// TenantInvitations is a globally accessible object for table tenant_invitations operations.
	TenantInvitations = tenantInvitationsDao{internal.NewTenantInvitationsDao()}
)

// Add your custom methods and functionality below.
