// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantUsageReservationsDao is the data access object for the table tenant_usage_reservations.
// You can define custom methods on it to extend its functionality as needed.
type tenantUsageReservationsDao struct {
	*internal.TenantUsageReservationsDao
}

var (
	// TenantUsageReservations is a globally accessible object for table tenant_usage_reservations operations.
	TenantUsageReservations = tenantUsageReservationsDao{internal.NewTenantUsageReservationsDao()}
)

// Add your custom methods and functionality below.
