// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantLifecycleJobsDao is the data access object for the table tenant_lifecycle_jobs.
// You can define custom methods on it to extend its functionality as needed.
type tenantLifecycleJobsDao struct {
	*internal.TenantLifecycleJobsDao
}

var (
	// TenantLifecycleJobs is a globally accessible object for table tenant_lifecycle_jobs operations.
	TenantLifecycleJobs = tenantLifecycleJobsDao{internal.NewTenantLifecycleJobsDao()}
)

// Add your custom methods and functionality below.
