// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantUsageCountersDao is the data access object for the table tenant_usage_counters.
// You can define custom methods on it to extend its functionality as needed.
type tenantUsageCountersDao struct {
	*internal.TenantUsageCountersDao
}

var (
	// TenantUsageCounters is a globally accessible object for table tenant_usage_counters operations.
	TenantUsageCounters = tenantUsageCountersDao{internal.NewTenantUsageCountersDao()}
)

// Add your custom methods and functionality below.
