// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantQuotasDao is the data access object for the table tenant_quotas.
// You can define custom methods on it to extend its functionality as needed.
type tenantQuotasDao struct {
	*internal.TenantQuotasDao
}

var (
	// TenantQuotas is a globally accessible object for table tenant_quotas operations.
	TenantQuotas = tenantQuotasDao{internal.NewTenantQuotasDao()}
)

// Add your custom methods and functionality below.
