// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantRepoSubscriptionsDao is the data access object for the table tenant_repo_subscriptions.
// You can define custom methods on it to extend its functionality as needed.
type tenantRepoSubscriptionsDao struct {
	*internal.TenantRepoSubscriptionsDao
}

var (
	// TenantRepoSubscriptions is a globally accessible object for table tenant_repo_subscriptions operations.
	TenantRepoSubscriptions = tenantRepoSubscriptionsDao{internal.NewTenantRepoSubscriptionsDao()}
)

// Add your custom methods and functionality below.
