// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// tenantMembershipsDao is the data access object for the table tenant_memberships.
// You can define custom methods on it to extend its functionality as needed.
type tenantMembershipsDao struct {
	*internal.TenantMembershipsDao
}

var (
	// TenantMemberships is a globally accessible object for table tenant_memberships operations.
	TenantMemberships = tenantMembershipsDao{internal.NewTenantMembershipsDao()}
)

// Add your custom methods and functionality below.
