// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// userPasswordCredentialsDao is the data access object for the table user_password_credentials.
// You can define custom methods on it to extend its functionality as needed.
type userPasswordCredentialsDao struct {
	*internal.UserPasswordCredentialsDao
}

var (
	// UserPasswordCredentials is a globally accessible object for table user_password_credentials operations.
	UserPasswordCredentials = userPasswordCredentialsDao{internal.NewUserPasswordCredentialsDao()}
)

// Add your custom methods and functionality below.
