// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

type userTotpBackupCodesDao struct {
	*internal.UserTotpBackupCodesDao
}

var UserTotpBackupCodes = userTotpBackupCodesDao{internal.NewUserTotpBackupCodesDao()}
