// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"multi-tenant-saas/internal/dao/internal"
)

// userIdentitiesDao is the data access object for the table user_identities.
// You can define custom methods on it to extend its functionality as needed.
type userIdentitiesDao struct {
	*internal.UserIdentitiesDao
}

var (
	// UserIdentities is a globally accessible object for table user_identities operations.
	UserIdentities = userIdentitiesDao{internal.NewUserIdentitiesDao()}
)

// Add your custom methods and functionality below.
