// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"repomind-temp/internal/dao/internal"
)

// webhookEventsDao is the data access object for the table webhook_events.
// You can define custom methods on it to extend its functionality as needed.
type webhookEventsDao struct {
	*internal.WebhookEventsDao
}

var (
	// WebhookEvents is a globally accessible object for table webhook_events operations.
	WebhookEvents = webhookEventsDao{internal.NewWebhookEventsDao()}
)

// Add your custom methods and functionality below.
