// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// AnalysisSnapshots defines the fields of table "analysis_snapshots" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var AnalysisSnapshots = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   1,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"commit_hash": {
		Index:   2,
		Name:    "commit_hash",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"analyze_job_id": {
		Index:   3,
		Name:    "analyze_job_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"files_count": {
		Index:   4,
		Name:    "files_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"symbols_count": {
		Index:   5,
		Name:    "symbols_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"relations_count": {
		Index:   6,
		Name:    "relations_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"processes_count": {
		Index:   7,
		Name:    "processes_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"communities_count": {
		Index:   8,
		Name:    "communities_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"stats": {
		Index:   9,
		Name:    "stats",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   10,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetAnalysisSnapshotsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetAnalysisSnapshotsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "analysis_snapshots", AnalysisSnapshots, schema...)
}
