// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// ApiKeys defines the fields of table "api_keys" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var ApiKeys = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"tenant_id": {
		Index:   1,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"user_id": {
		Index:   2,
		Name:    "user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   3,
		Name:    "name",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"key_hash": {
		Index:   4,
		Name:    "key_hash",
		Type:    "text",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"scopes": {
		Index:   5,
		Name:    "scopes",
		Type:    "_text",
		Null:    false,
		Key:     "",
		Default: "ARRAY[]::text[]",
		Extra:   "",
		Comment: "",
	},
	"last_used_at": {
		Index:   6,
		Name:    "last_used_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"expires_at": {
		Index:   7,
		Name:    "expires_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"revoked_at": {
		Index:   9,
		Name:    "revoked_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"key_prefix": {
		Index:   10,
		Name:    "key_prefix",
		Type:    "varchar(32)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_by_user_id": {
		Index:   11,
		Name:    "created_by_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetApiKeysTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetApiKeysTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "api_keys", ApiKeys, schema...)
}
