// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// Communities defines the fields of table "communities" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var Communities = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"id": {
		Index:   1,
		Name:    "id",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"label": {
		Index:   2,
		Name:    "label",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"cohesion": {
		Index:   3,
		Name:    "cohesion",
		Type:    "float8(53)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"symbol_count": {
		Index:   4,
		Name:    "symbol_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"keywords": {
		Index:   5,
		Name:    "keywords",
		Type:    "_text",
		Null:    false,
		Key:     "",
		Default: "ARRAY[]::text[]",
		Extra:   "",
		Comment: "",
	},
	"description": {
		Index:   6,
		Name:    "description",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   7,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetCommunitiesTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetCommunitiesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "communities", Communities, schema...)
}
