// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// GitCredentials defines the fields of table "git_credentials" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var GitCredentials = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"tenant_id": {
		Index:   1,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"owner_user_id": {
		Index:   2,
		Name:    "owner_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"provider": {
		Index:   3,
		Name:    "provider",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"base_url": {
		Index:   4,
		Name:    "base_url",
		Type:    "varchar(255)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"access_token_cipher": {
		Index:   5,
		Name:    "access_token_cipher",
		Type:    "bytea",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"refresh_token_cipher": {
		Index:   6,
		Name:    "refresh_token_cipher",
		Type:    "bytea",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"token_expires_at": {
		Index:   7,
		Name:    "token_expires_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"scopes": {
		Index:   8,
		Name:    "scopes",
		Type:    "_text",
		Null:    false,
		Key:     "",
		Default: "ARRAY[]::text[]",
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   9,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'active'::character varying",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   10,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   11,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"deleted_at": {
		Index:   12,
		Name:    "deleted_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetGitCredentialsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetGitCredentialsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "git_credentials", GitCredentials, schema...)
}
