// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PlanEntitlements defines the fields of table "plan_entitlements" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PlanEntitlements = map[string]*gdb.TableField{
	"plan": {
		Index:   0,
		Name:    "plan",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"feature_key": {
		Index:   1,
		Name:    "feature_key",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"enabled": {
		Index:   2,
		Name:    "enabled",
		Type:    "bool",
		Null:    false,
		Key:     "",
		Default: "true",
		Extra:   "",
		Comment: "",
	},
	"limit_value": {
		Index:   3,
		Name:    "limit_value",
		Type:    "int8(64)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   4,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   5,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   6,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetPlanEntitlementsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPlanEntitlementsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "plan_entitlements", PlanEntitlements, schema...)
}
