// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// ProcessSteps defines the fields of table "process_steps" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var ProcessSteps = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"process_id": {
		Index:   1,
		Name:    "process_id",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"step_index": {
		Index:   2,
		Name:    "step_index",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"symbol_uid": {
		Index:   3,
		Name:    "symbol_uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"relation_to_next": {
		Index:   4,
		Name:    "relation_to_next",
		Type:    "varchar(80)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetProcessStepsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetProcessStepsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "process_steps", ProcessSteps, schema...)
}
