// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// Processes defines the fields of table "processes" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var Processes = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"id": {
		Index:   1,
		Name:    "id",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"label": {
		Index:   2,
		Name:    "label",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"process_type": {
		Index:   3,
		Name:    "process_type",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"step_count": {
		Index:   4,
		Name:    "step_count",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"communities": {
		Index:   5,
		Name:    "communities",
		Type:    "_text",
		Null:    false,
		Key:     "",
		Default: "ARRAY[]::text[]",
		Extra:   "",
		Comment: "",
	},
	"entry_point_uid": {
		Index:   6,
		Name:    "entry_point_uid",
		Type:    "varchar(512)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"terminal_uid": {
		Index:   7,
		Name:    "terminal_uid",
		Type:    "varchar(512)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"summary": {
		Index:   8,
		Name:    "summary",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   9,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   10,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   11,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetProcessesTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetProcessesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "processes", Processes, schema...)
}
