// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// Relations defines the fields of table "relations" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var Relations = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   1,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"source_uid": {
		Index:   2,
		Name:    "source_uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"target_uid": {
		Index:   3,
		Name:    "target_uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"relation_type": {
		Index:   4,
		Name:    "relation_type",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"confidence": {
		Index:   5,
		Name:    "confidence",
		Type:    "float8(53)",
		Null:    false,
		Key:     "",
		Default: "1.0",
		Extra:   "",
		Comment: "",
	},
	"reason": {
		Index:   6,
		Name:    "reason",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"properties": {
		Index:   7,
		Name:    "properties",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetRelationsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetRelationsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "relations", Relations, schema...)
}
