// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// RepoAccessGrants defines the fields of table "repo_access_grants" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var RepoAccessGrants = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"subject_type": {
		Index:   1,
		Name:    "subject_type",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"subject_id": {
		Index:   2,
		Name:    "subject_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"permission": {
		Index:   3,
		Name:    "permission",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"source": {
		Index:   4,
		Name:    "source",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"external_account_id": {
		Index:   5,
		Name:    "external_account_id",
		Type:    "varchar(255)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"synced_at": {
		Index:   6,
		Name:    "synced_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"expires_at": {
		Index:   7,
		Name:    "expires_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   9,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetRepoAccessGrantsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetRepoAccessGrantsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "repo_access_grants", RepoAccessGrants, schema...)
}
