// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// RepoBranches defines the fields of table "repo_branches" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var RepoBranches = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   1,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"branch_name": {
		Index:   2,
		Name:    "branch_name",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"commit_hash": {
		Index:   3,
		Name:    "commit_hash",
		Type:    "varchar(80)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"is_default": {
		Index:   4,
		Name:    "is_default",
		Type:    "bool",
		Null:    false,
		Key:     "",
		Default: "false",
		Extra:   "",
		Comment: "",
	},
	"last_seen_at": {
		Index:   5,
		Name:    "last_seen_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetRepoBranchesTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetRepoBranchesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "repo_branches", RepoBranches, schema...)
}
