// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// Symbols defines the fields of table "symbols" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var Symbols = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"uid": {
		Index:   1,
		Name:    "uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"file_id": {
		Index:   2,
		Name:    "file_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   3,
		Name:    "name",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"kind": {
		Index:   4,
		Name:    "kind",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"file_path": {
		Index:   5,
		Name:    "file_path",
		Type:    "varchar(1024)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"start_line": {
		Index:   6,
		Name:    "start_line",
		Type:    "int4(32)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"end_line": {
		Index:   7,
		Name:    "end_line",
		Type:    "int4(32)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"content": {
		Index:   8,
		Name:    "content",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"parameter_count": {
		Index:   9,
		Name:    "parameter_count",
		Type:    "int4(32)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"return_type": {
		Index:   10,
		Name:    "return_type",
		Type:    "varchar(512)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"properties": {
		Index:   11,
		Name:    "properties",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"content_hash": {
		Index:   12,
		Name:    "content_hash",
		Type:    "varchar(128)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   13,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   14,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetSymbolsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetSymbolsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "symbols", Symbols, schema...)
}
