// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// SymbolCommunities defines the fields of table "symbol_communities" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var SymbolCommunities = map[string]*gdb.TableField{
	"repo_id": {
		Index:   0,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"symbol_uid": {
		Index:   1,
		Name:    "symbol_uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"community_id": {
		Index:   2,
		Name:    "community_id",
		Type:    "varchar(120)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"score": {
		Index:   3,
		Name:    "score",
		Type:    "float8(53)",
		Null:    false,
		Key:     "",
		Default: "1.0",
		Extra:   "",
		Comment: "",
	},
}

// SetSymbolCommunitiesTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetSymbolCommunitiesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "symbol_communities", SymbolCommunities, schema...)
}
