// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// SymbolSearch defines the fields of table "symbol_search" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var SymbolSearch = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   1,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"symbol_uid": {
		Index:   2,
		Name:    "symbol_uid",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   3,
		Name:    "name",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"kind": {
		Index:   4,
		Name:    "kind",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"file_path": {
		Index:   5,
		Name:    "file_path",
		Type:    "varchar(1024)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"content": {
		Index:   6,
		Name:    "content",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"summary": {
		Index:   7,
		Name:    "summary",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"community_id": {
		Index:   8,
		Name:    "community_id",
		Type:    "varchar(120)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"process_id": {
		Index:   9,
		Name:    "process_id",
		Type:    "varchar(120)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name_tsv": {
		Index:   10,
		Name:    "name_tsv",
		Type:    "tsvector",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"content_tsv": {
		Index:   11,
		Name:    "content_tsv",
		Type:    "tsvector",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"embedding": {
		Index:   12,
		Name:    "embedding",
		Type:    "vector",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"embedding_model": {
		Index:   13,
		Name:    "embedding_model",
		Type:    "varchar(120)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"embedding_dimension": {
		Index:   14,
		Name:    "embedding_dimension",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "1536",
		Extra:   "",
		Comment: "",
	},
	"search_boost": {
		Index:   15,
		Name:    "search_boost",
		Type:    "numeric(8)",
		Null:    false,
		Key:     "",
		Default: "1.0",
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   16,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   17,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   18,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetSymbolSearchTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetSymbolSearchTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "symbol_search", SymbolSearch, schema...)
}
