// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// TenantQuotas defines the fields of table "tenant_quotas" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var TenantQuotas = map[string]*gdb.TableField{
	"tenant_id": {
		Index:   0,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"max_repos": {
		Index:   1,
		Name:    "max_repos",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"max_symbols": {
		Index:   2,
		Name:    "max_symbols",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"max_storage_mb": {
		Index:   3,
		Name:    "max_storage_mb",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"max_daily_requests": {
		Index:   4,
		Name:    "max_daily_requests",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "1000",
		Extra:   "",
		Comment: "",
	},
	"max_concurrent_jobs": {
		Index:   5,
		Name:    "max_concurrent_jobs",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "1",
		Extra:   "",
		Comment: "",
	},
	"current_repos": {
		Index:   6,
		Name:    "current_repos",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"current_symbols": {
		Index:   7,
		Name:    "current_symbols",
		Type:    "int8(64)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"current_storage_mb": {
		Index:   8,
		Name:    "current_storage_mb",
		Type:    "int8(64)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   9,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetTenantQuotasTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantQuotasTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenant_quotas", TenantQuotas, schema...)
}
