// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// Tenants defines the fields of table "tenants" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var Tenants = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   1,
		Name:    "name",
		Type:    "varchar(100)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"slug": {
		Index:   2,
		Name:    "slug",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"plan": {
		Index:   3,
		Name:    "plan",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'free'::character varying",
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   4,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'active'::character varying",
		Extra:   "",
		Comment: "",
	},
	"max_repos": {
		Index:   5,
		Name:    "max_repos",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "5",
		Extra:   "",
		Comment: "",
	},
	"max_symbols": {
		Index:   6,
		Name:    "max_symbols",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "100000",
		Extra:   "",
		Comment: "",
	},
	"max_storage_mb": {
		Index:   7,
		Name:    "max_storage_mb",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "1024",
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   8,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   9,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   10,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"deleted_at": {
		Index:   11,
		Name:    "deleted_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetTenantsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenants", Tenants, schema...)
}
