// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// TenantLifecycleJobs defines the fields of table "tenant_lifecycle_jobs" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var TenantLifecycleJobs = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"tenant_id": {
		Index:   1,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"type": {
		Index:   2,
		Name:    "type",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   3,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'pending'::character varying",
		Extra:   "",
		Comment: "",
	},
	"requested_by_user_id": {
		Index:   4,
		Name:    "requested_by_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"scheduled_at": {
		Index:   5,
		Name:    "scheduled_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"started_at": {
		Index:   6,
		Name:    "started_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"finished_at": {
		Index:   7,
		Name:    "finished_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"error_message": {
		Index:   8,
		Name:    "error_message",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: "''::text",
		Extra:   "",
		Comment: "",
	},
	"artifact_uri": {
		Index:   9,
		Name:    "artifact_uri",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: "''::text",
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   10,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   11,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   12,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetTenantLifecycleJobsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantLifecycleJobsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenant_lifecycle_jobs", TenantLifecycleJobs, schema...)
}
