// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// TenantRepoSubscriptions defines the fields of table "tenant_repo_subscriptions" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var TenantRepoSubscriptions = map[string]*gdb.TableField{
	"tenant_id": {
		Index:   0,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   1,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"added_by_user_id": {
		Index:   2,
		Name:    "added_by_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"credential_id": {
		Index:   3,
		Name:    "credential_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"purpose": {
		Index:   4,
		Name:    "purpose",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'workspace'::character varying",
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   5,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'active'::character varying",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   6,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   7,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"deleted_at": {
		Index:   8,
		Name:    "deleted_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetTenantRepoSubscriptionsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantRepoSubscriptionsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenant_repo_subscriptions", TenantRepoSubscriptions, schema...)
}
