// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// TenantUsageCounters defines the fields of table "tenant_usage_counters" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var TenantUsageCounters = map[string]*gdb.TableField{
	"tenant_id": {
		Index:   0,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"metric": {
		Index:   1,
		Name:    "metric",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"period_start": {
		Index:   2,
		Name:    "period_start",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "'1970-01-01 00:00:00+00'::timestamp with time zone",
		Extra:   "",
		Comment: "",
	},
	"period_end": {
		Index:   3,
		Name:    "period_end",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "'2999-12-31 00:00:00+00'::timestamp with time zone",
		Extra:   "",
		Comment: "",
	},
	"used": {
		Index:   4,
		Name:    "used",
		Type:    "int8(64)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"reserved": {
		Index:   5,
		Name:    "reserved",
		Type:    "int8(64)",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"limit_snapshot": {
		Index:   6,
		Name:    "limit_snapshot",
		Type:    "int8(64)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   7,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetTenantUsageCountersTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantUsageCountersTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenant_usage_counters", TenantUsageCounters, schema...)
}
