// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// TenantInvitations defines the fields of table "tenant_invitations" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var TenantInvitations = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"tenant_id": {
		Index:   1,
		Name:    "tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"invitee_email": {
		Index:   2,
		Name:    "invitee_email",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"invitee_user_id": {
		Index:   3,
		Name:    "invitee_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"role": {
		Index:   4,
		Name:    "role",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   5,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'pending'::character varying",
		Extra:   "",
		Comment: "",
	},
	"token_hash": {
		Index:   6,
		Name:    "token_hash",
		Type:    "text",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"invited_by_user_id": {
		Index:   7,
		Name:    "invited_by_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"accepted_by_user_id": {
		Index:   8,
		Name:    "accepted_by_user_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"message": {
		Index:   9,
		Name:    "message",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: "''::text",
		Extra:   "",
		Comment: "",
	},
	"expires_at": {
		Index:   10,
		Name:    "expires_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"accepted_at": {
		Index:   11,
		Name:    "accepted_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"declined_at": {
		Index:   12,
		Name:    "declined_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"revoked_at": {
		Index:   13,
		Name:    "revoked_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"resent_at": {
		Index:   14,
		Name:    "resent_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"metadata": {
		Index:   15,
		Name:    "metadata",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   16,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   17,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetTenantInvitationsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetTenantInvitationsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "tenant_invitations", TenantInvitations, schema...)
}
