// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// UserPasswordCredentials defines the fields of table "user_password_credentials" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var UserPasswordCredentials = map[string]*gdb.TableField{
	"user_id": {
		Index:   0,
		Name:    "user_id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"password_hash": {
		Index:   1,
		Name:    "password_hash",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"hash_alg": {
		Index:   2,
		Name:    "hash_alg",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'bcrypt'::character varying",
		Extra:   "",
		Comment: "",
	},
	"hash_cost": {
		Index:   3,
		Name:    "hash_cost",
		Type:    "int4(32)",
		Null:    false,
		Key:     "",
		Default: "12",
		Extra:   "",
		Comment: "",
	},
	"password_changed_at": {
		Index:   4,
		Name:    "password_changed_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   5,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   6,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetUserPasswordCredentialsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetUserPasswordCredentialsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "user_password_credentials", UserPasswordCredentials, schema...)
}
