// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// UserTotpConfigs defines the fields of table "user_totp_configs" with their properties.
var UserTotpConfigs = map[string]*gdb.TableField{
	"id":               {Index: 0, Name: "id", Type: "uuid", Null: false, Key: "pri", Default: "gen_random_uuid()", Extra: "", Comment: ""},
	"user_id":          {Index: 1, Name: "user_id", Type: "uuid", Null: false, Key: "uni", Default: nil, Extra: "", Comment: ""},
	"secret_encrypted": {Index: 2, Name: "secret_encrypted", Type: "text", Null: false, Key: "", Default: nil, Extra: "", Comment: ""},
	"enabled":          {Index: 3, Name: "enabled", Type: "bool", Null: false, Key: "", Default: "false", Extra: "", Comment: ""},
	"enabled_at":       {Index: 4, Name: "enabled_at", Type: "timestamptz", Null: true, Key: "", Default: nil, Extra: "", Comment: ""},
	"created_at":       {Index: 5, Name: "created_at", Type: "timestamptz", Null: false, Key: "", Default: "now()", Extra: "", Comment: ""},
	"updated_at":       {Index: 6, Name: "updated_at", Type: "timestamptz", Null: false, Key: "", Default: "now()", Extra: "", Comment: ""},
}

// SetUserTotpConfigsTableFields registers the table fields definition to the database instance.
func SetUserTotpConfigsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "user_totp_configs", UserTotpConfigs, schema...)
}
