// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// UserTotpBackupCodes defines the fields of table "user_totp_backup_codes" with their properties.
var UserTotpBackupCodes = map[string]*gdb.TableField{
	"id":         {Index: 0, Name: "id", Type: "uuid", Null: false, Key: "pri", Default: "gen_random_uuid()", Extra: "", Comment: ""},
	"user_id":    {Index: 1, Name: "user_id", Type: "uuid", Null: false, Key: "mul", Default: nil, Extra: "", Comment: ""},
	"code_hash":  {Index: 2, Name: "code_hash", Type: "text", Null: false, Key: "", Default: nil, Extra: "", Comment: ""},
	"used_at":    {Index: 3, Name: "used_at", Type: "timestamptz", Null: true, Key: "", Default: nil, Extra: "", Comment: ""},
	"created_at": {Index: 4, Name: "created_at", Type: "timestamptz", Null: false, Key: "", Default: "now()", Extra: "", Comment: ""},
}

// SetUserTotpBackupCodesTableFields registers the table fields definition to the database instance.
func SetUserTotpBackupCodesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "user_totp_backup_codes", UserTotpBackupCodes, schema...)
}
