// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// UserIdentities defines the fields of table "user_identities" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var UserIdentities = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"user_id": {
		Index:   1,
		Name:    "user_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"provider": {
		Index:   2,
		Name:    "provider",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"auth_id": {
		Index:   3,
		Name:    "auth_id",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"email": {
		Index:   4,
		Name:    "email",
		Type:    "varchar(255)",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"email_verified": {
		Index:   5,
		Name:    "email_verified",
		Type:    "bool",
		Null:    false,
		Key:     "",
		Default: "false",
		Extra:   "",
		Comment: "",
	},
	"raw_profile": {
		Index:   6,
		Name:    "raw_profile",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: "'{}'::jsonb",
		Extra:   "",
		Comment: "",
	},
	"last_login_at": {
		Index:   7,
		Name:    "last_login_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"updated_at": {
		Index:   9,
		Name:    "updated_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
}

// SetUserIdentitiesTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetUserIdentitiesTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "user_identities", UserIdentities, schema...)
}
