// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// WebhookEvents defines the fields of table "webhook_events" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var WebhookEvents = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "uuid",
		Null:    false,
		Key:     "pri",
		Default: "gen_random_uuid()",
		Extra:   "",
		Comment: "",
	},
	"received_by_tenant_id": {
		Index:   1,
		Name:    "received_by_tenant_id",
		Type:    "uuid",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"repo_id": {
		Index:   2,
		Name:    "repo_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"provider": {
		Index:   3,
		Name:    "provider",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "uni",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"event_type": {
		Index:   4,
		Name:    "event_type",
		Type:    "varchar(80)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"delivery_id": {
		Index:   5,
		Name:    "delivery_id",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"payload_hash": {
		Index:   6,
		Name:    "payload_hash",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"payload": {
		Index:   7,
		Name:    "payload",
		Type:    "jsonb",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   8,
		Name:    "status",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: "'received'::character varying",
		Extra:   "",
		Comment: "",
	},
	"analyze_job_id": {
		Index:   9,
		Name:    "analyze_job_id",
		Type:    "uuid",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"received_at": {
		Index:   10,
		Name:    "received_at",
		Type:    "timestamptz",
		Null:    false,
		Key:     "",
		Default: "now()",
		Extra:   "",
		Comment: "",
	},
	"processed_at": {
		Index:   11,
		Name:    "processed_at",
		Type:    "timestamptz",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"error_msg": {
		Index:   12,
		Name:    "error_msg",
		Type:    "text",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
}

// SetWebhookEventsTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetWebhookEventsTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "webhook_events", WebhookEvents, schema...)
}
